import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { sanityClient, urlFor } from "../sanity";
import { Collection } from "../typings";
import Link from "next/link";
import { useDisconnect, useMetamask, useAddress } from "@thirdweb-dev/react";

interface Props {
  collections: Collection[];
}

const Home = ({ collections }: Props) => {
  const address = useAddress();
  const connectToMetamask = useMetamask();
  const disconnectFromMetmask = useDisconnect();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-black w-full flex h-10 items-center justify-end space-x-8 sticky top-0 z-10 shadow-md shadow-white/20'>
        <Link href={"/about"} passHref>
          <button className='text-white font-semibold'>About</button>
        </Link>
        <Link href={"/find"} passHref>
          <button className='text-white font-semibold pr-6'>Find</button>
        </Link>
      </div>
      <div className='flex flex-col items-center max-w-7xl mx-auto py-20 px-10 bg-gradient-to-br from-neutral-800 to-black bg-cover'>
        <div className='flex md:flex-col lg:flex-row mb-10 mt-10 items-center justify-between'>
          <h1 className=' lg:text-4xl md:text-4xl lg:mr-10 lg:mt-20cd lg:pr-14 text-2xl font-extralight text-center mb-6 text-gray-300'>
            <span className='font-bold text-gray-300 underline'>
              Crazy APES
            </span>{" "}
            NFT Marketplace
          </h1>
          <div className='hidden md:grid lg:grid-cols-2 lg:gap-5 md:grid-cols-4 md:gap-3'>
            <div className='md:order-0'>
              <Image
                src='/nft2.png'
                layout='responsive'
                height={32}
                width={32}
                alt=''
                className='rounded-lg'
              />
            </div>

            <div className='w-32 h-32 bg-red-300 rounded-lg md:order-1 lg:order-1' />
            <div className='w-32 h-32 bg-cyan-300 rounded-lg lg:order-2' />

            <div className='md:order-2 lg:order-3'>
              <Image
                src='/nft1.jpg'
                layout='responsive'
                height={32}
                width={32}
                alt=''
                className='rounded-lg'
              />
            </div>

            <div className='lg:order-4'>
              <Image
                src='/turnhead.png'
                layout='responsive'
                height={32}
                width={32}
                alt=''
                className='rounded-lg md:order-3'
              />
            </div>

            <div className='w-32 h-32 bg-fuchsia-700 rounded-lg lg:order-5' />
            <div className='w-32 h-32 bg-lime-200 rounded-lg lg:order-6' />

            <div className='lg:order-7'>
              <Image
                src='/simpson.jpg'
                layout='responsive'
                height={32}
                width={32}
                alt=''
                className='rounded-lg'
              />
            </div>
          </div>
        </div>
        <h1 className='text-xl md:text-4xl text-red-200 font-semibold mb-8'>
          {" "}
          <span className='font-bold text-blue-400'>Discover</span> new NFTs
        </h1>
        <main className='bg-slate-100/60 px-10 pt-10 pb-5 shadow-xl shadow-blue-500/60 rounded-sm'>
          <div className='grid space-x-3  md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4'>
            {collections.map((collection) => (
              <Link
                key={collection._id}
                href={`/nft/${collection.slug.current}`}
                passHref
              >
                <div className='flex flex-col items-center cursor-pointer hover:scale-105 transition-all duration-75 ease-in-out mb-6 group'>
                  <div className='bg-gradient-to-br from-cyan-300 to-gray-800 p-2 rounded-md'>
                    <div className='w-32 h-32 relative'>
                      <Image
                        className='rounded-md'
                        alt=''
                        src={urlFor(collection.mainImage).url()}
                        layout='fill'
                      />
                    </div>
                  </div>
                  <div className='text-center'>
                    <h2 className='font-semibold text-2xl'>
                      {collection.nftCollectionName}
                    </h2>
                    <p className='text-gray-800 font-semibold group-hover:underline'>
                      {collection.description}
                    </p>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </main>
      </div>
      <h2 className='text-white text-sm font-semibold bg-black text-center'>
        Made by JayDee
      </h2>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const query = `*[_type == 'collection']{
    _id,
    title,
    address,
    description,
  nftCollectionName,
    slug{
    current
  },
    mainImage{
    asset
  },
    creator->{
     _id,
    name,
    address,
    slug{
    current
   }
  }
}`;

  const collections = await sanityClient.fetch(query);

  return {
    props: {
      collections,
    },
  };
};
